name: Docker Image CI

on:
  push:
    branches: [ "feat/*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile/Dockerfile --tag ghcr.io/Ashishkasaudhan/nginx:$(date +%s)